// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtc2bc73ZBBu10SfnCK9o5Yo-rWNRkoyU',
    appId: '1:471900846848:web:023b34126296d347e651e5',
    messagingSenderId: '471900846848',
    projectId: 'keygenapp-5daa3',
    authDomain: 'keygenapp-5daa3.firebaseapp.com',
    storageBucket: 'keygenapp-5daa3.firebasestorage.app',
    measurementId: 'G-VWHB7VXGCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJAKjQb7vsAykhrS9mPOkf5D2gsvWohYw',
    appId: '1:471900846848:android:fd76fc98765abdb1e651e5',
    messagingSenderId: '471900846848',
    projectId: 'keygenapp-5daa3',
    storageBucket: 'keygenapp-5daa3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeWPYox5pU_JL7n26x-6XMXGeSdpmPQMQ',
    appId: '1:471900846848:ios:fa1c2f59675681cbe651e5',
    messagingSenderId: '471900846848',
    projectId: 'keygenapp-5daa3',
    storageBucket: 'keygenapp-5daa3.firebasestorage.app',
    iosBundleId: 'com.example.keyGeneration',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeWPYox5pU_JL7n26x-6XMXGeSdpmPQMQ',
    appId: '1:471900846848:ios:fa1c2f59675681cbe651e5',
    messagingSenderId: '471900846848',
    projectId: 'keygenapp-5daa3',
    storageBucket: 'keygenapp-5daa3.firebasestorage.app',
    iosBundleId: 'com.example.keyGeneration',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtc2bc73ZBBu10SfnCK9o5Yo-rWNRkoyU',
    appId: '1:471900846848:web:0c11a5502bf9e83de651e5',
    messagingSenderId: '471900846848',
    projectId: 'keygenapp-5daa3',
    authDomain: 'keygenapp-5daa3.firebaseapp.com',
    storageBucket: 'keygenapp-5daa3.firebasestorage.app',
    measurementId: 'G-QSMEJ8D2Q3',
  );
}
